# Generated by Django 3.0.3 on 2020-02-06 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190701_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('description', models.CharField(default=None, max_length=200)),
                ('org', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('content', models.CharField(default=None, max_length=1000)),
                ('attachmentUrl', models.CharField(default=None, max_length=500)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('org', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('content', models.CharField(default=None, max_length=1000)),
                ('attachmentUrl', models.CharField(default=None, max_length=500)),
                ('org', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.RenameField(
            model_name='orguser',
            old_name='system_user',
            new_name='systemUser',
        ),
        migrations.RemoveField(
            model_name='orguser',
            name='username',
        ),
        migrations.AddField(
            model_name='orguser',
            name='contactNumber',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='orguser',
            name='email',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='orguser',
            name='firstName',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='orguser',
            name='lastName',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='OrgUserNotificationMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrgUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OrgUser')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Notification')),
            ],
        ),
        migrations.CreateModel(
            name='OrgUserEventMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrgUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OrgUser')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
            ],
        ),
        migrations.CreateModel(
            name='OrgUserBatchMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrgUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.OrgUser')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Batch')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('description', models.CharField(default=None, max_length=200)),
                ('org', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='EventLocationMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Location')),
            ],
        ),
    ]
