# Generated by Django 3.0.4 on 2020-03-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200206_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='attachmentUrl',
            new_name='attachment_url',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='attachmentUrl',
            new_name='attachment_url',
        ),
        migrations.RenameField(
            model_name='orguser',
            old_name='contactNumber',
            new_name='contact_number',
        ),
        migrations.RenameField(
            model_name='orguser',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='orguser',
            old_name='lastName',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='orguser',
            old_name='systemUser',
            new_name='system_user',
        ),
        migrations.RenameField(
            model_name='orguserbatchmapping',
            old_name='OrgUser',
            new_name='org_user',
        ),
        migrations.RenameField(
            model_name='orgusereventmapping',
            old_name='OrgUser',
            new_name='org_user',
        ),
        migrations.RenameField(
            model_name='orgusernotificationmapping',
            old_name='OrgUser',
            new_name='org_user',
        ),
    ]
